updated Jenkinsfile script with OWASP dependencies updated arguments

diff --git a/web-bank-app/Jenkinsfile b/web-bank-app/Jenkinsfile
--- a/web-bank-app/Jenkinsfile
+++ b/web-bank-app/Jenkinsfile
@@ -91,17 +91,22 @@ pipeline {
                           --out dependency-check-report \
                           --data /opt/odc-data \
                           --propertyfile /opt/dependency-check/conf/dependency-check.properties \
-                          --nvdApiKey $NVD_API_KEY || true
+                          --suppression dependency-check-suppression.xml \
+                          --nvdApiKey $NVD_API_KEY
 
-                        echo "OWASP scan completed (exit code ignored intentionally)"
-                 '''
+                        EXIT_CODE=$?
+
+                        if [ $EXIT_CODE -ne 0 ]; then
+                            echo "OWASP found vulnerabilities or DB errors. Failing the build."
+                            exit 1
+                        fi
+                    '''
         }
     }
            post {
                always {
-                   archiveArtifacts artifacts: 'dependency-check-report/**',
-                              fingerprint: true,
-                              allowEmptyArchive: true
+                   archiveArtifacts artifacts: 'dependency-check-report/**', fingerprint: true
+                              
         }
     }
 }
